package com.example.hauiTrash.entity;

import jakarta.persistence.*;
import lombok.*;
import lombok.experimental.SuperBuilder;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;


import java.util.List;

@Getter @Setter
@NoArgsConstructor @AllArgsConstructor
@Entity
@SuperBuilder
@Table(name="trash_item_knowledge")
public class TrashItemKnowledge extends BaseEntity {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "trash_item_id", nullable = false)
    private TrashItem trashItem;

    private String material;

    @Lob
    private String note;
    @Lob
    private String action;
    @Lob
    private String impact;
    @Lob
    private String toxicity;

    @JdbcTypeCode(SqlTypes.JSON)
    @Column(name = "safe_steps_json")
    private List<String> safeSteps;

    @Column(nullable = false, length = 30)
    private String source; // AI/MANUAL

    @Column(length = 80)
    private String model;

    @Column(nullable = false)
    private Integer version;

    @Column(name = "is_active", nullable = false)
    private Boolean isActive;

    /**
     * RAG: Vector embedding generated by Gemini text-embedding-004.
     * Stored as JSON array of floats for cosine similarity search.
     */
    @JdbcTypeCode(SqlTypes.JSON)
    @Column(name = "embedding_json", columnDefinition = "JSON")
    private List<Float> embeddingJson;
}
