package com.example.hauiTrash.dto;

import com.example.hauiTrash.entity.TrashItem;
import com.example.hauiTrash.entity.TrashItemKnowledge;
import com.example.hauiTrash.entity.TrashType;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class VisualRagResult {
    private TrashItem trashItem;
    private TrashType trashType;
    private TrashItemKnowledge knowledge;
    private Float mappingConfidence;

    // RAG metadata
    /** Cosine similarity score from embedding search (0.0 ~ 1.0) */
    private Float ragSimilarityScore;
    /** Source of retrieval: RAG_SEMANTIC, RAG_EXACT, FALLBACK_DB */
    private String ragSource;
    /** Augmented knowledge generated by LLM from retrieved context */
    private TrashItemKnowledge augmentedKnowledge;
}